version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db

  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: user_db_mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  trino:
    image: trinodb/trino:latest
    ports:
      - "8081:8081"
    volumes:
      - ./trino-config/catalog:/etc/trino

  iceberg:
    image: airbyte/destination-iceberg:latest
    container_name: iceberg_container
    ports:
      - "8888:8888"
    environment:
      - ICEBERG_HOME=/opt/iceberg
    volumes:
      - ./iceberg-config/catalog:/opt/iceberg/config

volumes:
  mongo-data:
    driver: local
  mysql_data:
    driver: local
